### ISSUE TITLE
增加微应用关闭按钮tinColor的设置和微应用的WKwebView的背景颜色设置

### ISSUE THREAD

**Issue by zjqCool** [alitajs/micro-app-ios-framework#1]

**Comment by falcon11** [comment]
已支持，使用方法看文档
https://micro.alitajs.com/sdk/ui#%E8%AE%BE%E7%BD%AE%E5%AF%BC%E8%88%AA%E6%A0%8F
https://micro.alitajs.com/sdk/ui#%E8%AE%BE%E7%BD%AE-webview-%E8%83%8C%E6%99%AF%E8%89%B2
