### ISSUE TITLE
BUG： AlitaWebViewController创建未执行viewDidLoad，dealloc会崩溃

### ISSUE THREAD

**Issue by zjqCool** [alitajs/micro-app-ios-framework#5]
建议
- (void)dealloc {
    [AlitaBridgeManager.sharedInstance removeWVJSBridge:self.webViewJSBridge];
    @try {
        [self.webView removeObserver:self forKeyPath:@"title" context:nil];
        [self.webView removeObserver:self forKeyPath:@"canGoBack" context:nil];
       }
       @catch(NSException *exception) {
           NSLog(@"--%@", exception);
       }
    NSLog(@"");
}

**Comment by falcon11** [comment]
0.5 版本已修复
